In [2]:
import numpy as np
import random

### Create Grid

In [47]:
DIAMOND_TYPES = ['A', 'D', 'H'] # A: Attack, D: Defend, H: Heal
class Player:
    def __init__(self, name):
        self.name = name
        self.hp = 100
        self.armor = 10
    
    def attack(self, dame):
        total_dame = max(1, dame - self.armor)
        self.hp -= total_dame
        print(f'{self.name} is attacked {total_dame} dame')
    def heal(self, hp_heal):
        self.hp = min(100, self.hp + hp_heal)
        print(f'{self.name} heal {self.hp}')
    def defend(self, armor_n):
        self.armor = min(75, self.armor + armor_n)
        print(f'{self.name} buff {self.armor}')
# hàm khởi tạo bảng ramdon, với điều kiện tránh 3 viên kim cương giống nhau liên tiếp
def Grid_Board(size):
    grid = np.random.choice(DIAMOND_TYPES,(size, size))
    for i in range(size):
        for j in range(size):
            # kiểm tra để tránh 3 giá trị trùng lặp trở lên của một cột
            if i <= (size-3) and grid[i][j] == grid[i + 1][j] == grid[i + 2][j]:
                new_values = [x for x in DIAMOND_TYPES if x != grid[i][j]]
                grid[i + 1][j] = random.choice(new_values)
            # kiểm tra để tránh 3 giá trị trùng lặp trở lên của một hàng
            if j <= (size-3) and grid[i][j] == grid[i][j + 1] == grid[i][j + 2]:
                new_values = [x for x in DIAMOND_TYPES if x != grid[i][j]]
                grid[i][j + 1] = random.choice(new_values)
    return grid

# hàm check điều kiện hoán đổi
def check_swap_condition(grid):
    rows, cols = grid.shape
    # check điều kiện về hàng
    for i in range(rows):
        for j in range(cols - 2):
            if grid[i][j] == grid[i][j+1] == grid[i][j+2]:
                return True
    # check điều kiện về cột
    for i in range(cols - 2):
        for j in range(rows):
            if  grid[i][j] == grid[i+1][j] == grid[i+2][j]:
                return True
    return False
# hoán đổi hai viên kim cương
def check_match(grid, x1, y1, x2, y2):
    new_grid = np.copy(grid)
    new_grid[x1][y1], new_grid[x2][y2] = new_grid[x2][y2], new_grid[x1][y1]
    if(check_swap_condition(new_grid)):
        return new_grid
    else: return grid
    

In [48]:
a = Grid_Board(10)
a

array([['A', 'A', 'H', 'A', 'H', 'D', 'A', 'D', 'H', 'H'],
       ['D', 'H', 'D', 'H', 'A', 'H', 'H', 'A', 'D', 'A'],
       ['D', 'A', 'H', 'A', 'H', 'D', 'A', 'A', 'H', 'D'],
       ['A', 'A', 'D', 'A', 'A', 'H', 'A', 'H', 'A', 'A'],
       ['A', 'H', 'A', 'H', 'D', 'A', 'D', 'A', 'A', 'H'],
       ['H', 'D', 'D', 'H', 'H', 'A', 'A', 'H', 'H', 'D'],
       ['A', 'H', 'H', 'A', 'D', 'H', 'D', 'H', 'A', 'A'],
       ['H', 'D', 'A', 'D', 'H', 'A', 'H', 'D', 'D', 'H'],
       ['D', 'H', 'D', 'A', 'D', 'H', 'A', 'H', 'A', 'A'],
       ['A', 'H', 'A', 'H', 'D', 'H', 'H', 'D', 'D', 'A']], dtype='<U1')

In [41]:
grid_test = Grid_Board(10)
grid_test2 = grid_test.copy()
grid_test2

array([['D', 'H', 'A', 'H', 'A', 'H', 'D', 'H', 'D', 'H'],
       ['A', 'H', 'D', 'A', 'H', 'D', 'H', 'D', 'A', 'H'],
       ['D', 'A', 'H', 'A', 'H', 'A', 'H', 'A', 'D', 'A'],
       ['H', 'D', 'A', 'H', 'D', 'H', 'A', 'H', 'D', 'H'],
       ['D', 'H', 'A', 'H', 'A', 'D', 'H', 'A', 'D', 'A'],
       ['H', 'D', 'A', 'H', 'D', 'A', 'D', 'H', 'D', 'H'],
       ['A', 'D', 'A', 'D', 'H', 'D', 'A', 'D', 'H', 'A'],
       ['H', 'D', 'A', 'H', 'A', 'H', 'D', 'A', 'D', 'H'],
       ['A', 'H', 'A', 'D', 'A', 'D', 'H', 'A', 'H', 'D'],
       ['H', 'A', 'D', 'A', 'D', 'A', 'H', 'D', 'H', 'A']], dtype='<U1')

In [43]:
grid_test2
check_match(grid_test2, 2, 1, 2, 2)

array([['D', 'H', 'A', 'H', 'A', 'H', 'D', 'H', 'D', 'H'],
       ['A', 'H', 'D', 'A', 'H', 'D', 'H', 'D', 'A', 'H'],
       ['D', 'H', 'A', 'A', 'H', 'A', 'H', 'A', 'D', 'A'],
       ['H', 'D', 'A', 'H', 'D', 'H', 'A', 'H', 'D', 'H'],
       ['D', 'H', 'A', 'H', 'A', 'D', 'H', 'A', 'D', 'A'],
       ['H', 'D', 'A', 'H', 'D', 'A', 'D', 'H', 'D', 'H'],
       ['A', 'D', 'A', 'D', 'H', 'D', 'A', 'D', 'H', 'A'],
       ['H', 'D', 'A', 'H', 'A', 'H', 'D', 'A', 'D', 'H'],
       ['A', 'H', 'A', 'D', 'A', 'D', 'H', 'A', 'H', 'D'],
       ['H', 'A', 'D', 'A', 'D', 'A', 'H', 'D', 'H', 'A']], dtype='<U1')

In [36]:
x = np.array([[1, 2, 3],
             [2, 5, 2],
             [7, 8, 9]])
check_match(x, 0, 1, 1, 1)

array([[1, 5, 3],
       [2, 2, 2],
       [7, 8, 9]])

In [17]:
def check_match(board, x1, y1, x2, y2):
    # Hoán đổi 2 viên kim cương
    board[x1][y1], board[x2][y2] = board[x2][y2], board[x1][y1]
    
    # Kiểm tra hàng dọc và ngang sau khi hoán đổi
    matches = []
    for i in range(len(board)):
        for j in range(len(board[i])):
            # Kiểm tra hàng ngang
            if j <= len(board[i]) - 3 and board[i][j] == board[i][j + 1] == board[i][j + 2]:
                matches.append((i, j, board[i][j]))
            # Kiểm tra hàng dọc
            if i <= len(board) - 3 and board[i][j] == board[i + 1][j] == board[i + 2][j]:
                matches.append((i, j, board[i][j]))
    
    return matches


In [23]:
array = Grid_Board(10)
print(len(array))

10


In [54]:
Player_1 = Player('Pham Quan')
Player_2 = Player('Pham Hai')
Player_1.attack(20)
Player_1.hp

Pham Quan is attacked 10 dame


90

In [4]:
Grid_Board(10)

array([['H', 'D', 'A', 'H', 'D', 'A', 'H', 'A', 'H', 'A'],
       ['A', 'H', 'D', 'H', 'A', 'H', 'A', 'H', 'D', 'H'],
       ['D', 'A', 'H', 'D', 'H', 'D', 'H', 'D', 'A', 'D'],
       ['H', 'A', 'D', 'H', 'D', 'A', 'D', 'H', 'A', 'H'],
       ['D', 'H', 'D', 'A', 'H', 'D', 'H', 'A', 'H', 'D'],
       ['H', 'D', 'A', 'D', 'A', 'D', 'H', 'D', 'A', 'H'],
       ['D', 'H', 'A', 'H', 'D', 'H', 'A', 'H', 'D', 'A'],
       ['A', 'D', 'A', 'D', 'H', 'A', 'D', 'A', 'H', 'D'],
       ['H', 'D', 'H', 'A', 'H', 'D', 'A', 'H', 'D', 'A'],
       ['A', 'H', 'A', 'H', 'A', 'H', 'D', 'H', 'D', 'A']], dtype='<U1')

In [33]:
import numpy as np
import random

# Tạo ma trận 10x10 với các quy tắc ngăn ngừa ba phần tử giống nhau
def generate_matrix(size):
    grid = np.zeros((size, size), dtype=int)
    for i in range(size):
        for j in range(size):
            # Lấy giá trị trước đó trong hàng và cột
            values = {grid[i-1][j] if i > 0 else None,
                      grid[i][j-1] if j > 0 else None}
            # Chọn một giá trị không giống giá trị đã tồn tại
            value = random.choice([x for x in range(3) if x not in values])
            grid[i][j] = value
    return grid

# Ma trận 10x10
grid = generate_matrix(10)

# In ma trận ban đầu
print("Ma trận ban đầu:")
print(grid)


Ma trận ban đầu:
[[2 1 2 1 2 1 0 1 2 1]
 [1 0 1 2 1 0 1 0 1 0]
 [2 1 2 0 2 1 0 1 0 1]
 [0 2 0 1 0 2 1 2 1 2]
 [2 1 2 0 1 0 2 1 2 1]
 [0 2 1 2 0 1 0 2 1 0]
 [1 0 2 0 2 0 1 0 2 1]
 [2 1 0 1 0 2 0 1 0 2]
 [0 2 1 2 1 0 2 0 1 0]
 [1 0 2 1 2 1 0 1 2 1]]


array(['A', 'D', 'H'], dtype='<U1')